' Gambas module file

Public Sub Main()

    ShmMem.ForceDelete("Work")
    Dim work As New ShmMem(4200000, "Work")
    Dim tag As String
    Dim theQ As SHmQueue
    Dim keytag As String

    With work
        !TheQ = New ShmQueue(work, 0, True, "Queue Test one")
        TheQ = !TheQ
        keytag = TheQ.key_tag
        !Testy1 = "hello world"
        !Testy2 = 1
        !Testy3 = 2.6
        !TheQ.enqueue("1-0", 0, "Tag this 0")
        !TheQ.enqueue("23-6", 6, "Tag this 6")
        !TheQ.enqueue("S2-5", 5, "Tag this 5")
        !TheQ.EnQueue("3-4", 4, "Tag this 4")
        !TheQ.enqueue("S4-3", 3, "Tag this 3")
        !TheQ.enqueue("5-100", 100, "Tag this 100")

        For Each qe As Variant In !TheQ
            tag = !TheQ.key_tag
            Print qe, !TheQ.key, !TheQ.key_tag
        Next

        For Each qe As Variant In TheQ
            tag = !TheQ.key_tag
            Print qe, !TheQ.key, !TheQ.key_tag
        Next

        .PrintTree()

        Print "Queue contains:"
        For Each g As Variant In !TheQ
            Print g
        Next
        Print "End Queue, Start Dqueue"

        While !TheQ.Count
            Print "Popping =";; !TheQ.dequeue()
        Wend

        Print "End Dqueue, Queue Count ="; !TheQ.count
        !TheQ.enqueue("1-0", 0)
        !TheQ.enqueue("23-6", 6)
        !TheQ.enqueue("6-5", 5)
        !TheQ.EnQueue("32-8", 8)
        !TheQ.enqueue("s12-3", 3)
        !TheQ.enqueue("5-100", 100)
        !TheQ.enqueue("1-0", 0, "Tag this 0")
        !TheQ.enqueue("23-6", 6, "Tag this 6")
        !TheQ.enqueue("S2-5", 5, "Tag this 5")
        !TheQ.EnQueue("3-4", 4, "Tag this 4")
        !TheQ.enqueue("S4-3", 3, "Tag this 3")
        !TheQ.enqueue("5-100", 100, "Tag this 100")

        ' .PrintAllInfo()

        Print "Queue contains:"
        For Each g As Variant In !TheQ
            Print g, !TheQ.key, !TheQ.key_tag
        Next

        '  Dim mytask As New NewBGDequeue
        '  mytask.work = work
        '  Wait 0.001

        ' mytask.Wait()
        Stop

        .PrintAllInfo()

        Work = Null

    End With

    Print shmMem.GetObjectClass(Me).name;; "Completed"
    Quit

Catch
    Print "error";; Error.Text

End
