' Gambas module file

Public mqa As New ShmMem(1000000)

Public Sub Main()

    Dim r As Variant

    Print Application.id, "***************************** Start FgTask "
    Dim qa As New ShmQueue(mqa, 0, True, "Queue Test")
    Wait 0
    Print application.id, "***************************** Start Background task"
    Dim MTask As New NewQueueBG
    Wait 0
    Print application.id, "***************************** Start Loop test"
    Flush
    For i As Integer = 0 To 100
        qa.enqueue("hello dolly", 0, "Enqueue hello Dolly")
        qa.enqueue(1, 0, "Enqueue 1")
        qa.enqueue(2.4, 0, "Enqueue 2.4")
        If i Mod 10 = 0 Then Print Application.id, "FG ************************************", i
        While qa.Count
            r = qa.pop()
        Wend
        Wait 0.1
    Next

    MTask.Wait()

    mqa.PrintAllInfo()
    Print shmMem.GetObjectClass(Me).name;; "Completed"
    Quit

End
