' Gambas module file

Public Sub main()

    Dim TestFile As String = User.home &/ "vars" &/ "testlist"
    Dim mem As New ShmMem
    Dim AQueue As New ShmQueue(mem, 0, True, "This is a tag", True)
    Dim bQueue As ShmQueue
    Dim cQueue As ShmQueue
    Dim varfile As File

    For i As Integer = 0 To 20
        AQueue.push("Test Value" & Str(i), 200 + i, "entryTAg" & Str(i))
    Next

    varfile = Open testfile For Write Create
    Write #varfile, aQueue As Object
    Close varfile

    varfile = Open testfile For Read
    bQueue = Read #varfile As Object
    Close varfile

    varfile = Open testfile For Read
    cQueue = New ShmQueue(varfile)
    Close varfile

    While bQueue.count > 0
        Print bQueue.Pop();;
    Wend

    Quit 0

End
