' Gambas module file

Public Sub Main()

    Dim MyMem As New ShmMem
    Dim a As New Integer[5, 5, 5]
    Dim b As New ShmArray(MyMem, [5, 5, 5])

    a.Fill(222)

    With mymem
        !a = a                                   '' this will automatically convert the array to a shmarray in the shared space and copy the data
        a[1, 1, 1] = 500

        !a[1, 1, 1] = 600
        Print !a[1, 1, 1]
    End With
    Print mymem!a[1, 1, 1]
    Quit 0

End
