' Gambas module file

Public Sub main()

    Dim TestFile As String = User.home &/ "vars" &/ "testarray"
    Dim mem As New ShmMem
    Dim a As ShmArray = New ShmArray(mem, [3, 3, 3], "Test Message")
    Dim varfile As File

    ' Now set values in a linear fasion, could use subscripts, but this is faster
    For i As Integer = 0 To a.max
        a[i] = "Test Value" & i
    Next

    varfile = Open testfile For Write Create
    Write #varfile, a As Object
    Close #varfile

    varfile = Open testfile For Read
    Dim b As ShmArray
    b = Read #Varfile As Object
    If Error Then Print Error.text

    mem!a = a
    mem.SaveNativeVar("testNative", a, testfile & "Native")
    mem.SaveVar("a", testfile)
    mem.LoadVar(testfile, "testarray")
    mem.LoadVar(testfile & "Native")
    Print mem!testarray.Export()
    Dim g As Variant = mem!testNative
    mem.Close()
    Quit 0

End
