' Gambas module file

Public Vars As ShmSymbolTable

Public Sub main()

    ShmMemBlock.ForceDelete("mydata_Data")
    Dim varStore As New ShmMemBlock(1128000, "mydata_Data")
    ' varStore.debug = True

    Dim varMnge As New ShmManage(varStore)
    'varMnge.debug = True

    Dim MyVarMem As New ShmVarStorage(varMnge)
    'MyVarMem.Debug = True

    ShmMemBlock.ForceDelete("mydata_Symbols")
    Dim symStore As New ShmMemBlock(1000000, "mydata_Symbols")
    'symStore.Debug = True

    vars = New ShmSymbolTable(symStore, MyVarMem)
    'vars.debug = True

    Dim MyList As New ShmList(MyVarMem, 0, False, "Test The List")
    Dim MyQueue As New ShmQueue(MyVarMem, 0, False, "Test The Queue")

    Print "Symbol Storage length =";; symStore.length, MyList.count

    With vars
        !dog = 8
        !cow = 6
        !done = 0
        Print "Dog="; !dog, "Cow="; !cow, "Done="; !done

        Dim Ntask As New NotifyBGTask As "TheTask"
        Wait
        Dim Ntask2 As New NotifyBGTask As "TheTask2"
        Wait

        vars.Notify("dog", Me)
        vars.Notify("Cow", Me)
        'vars.NotifyStop("dog")

        varMnge._PrintBlocks(MyVarMem)
        varMnge._PrintFreeList()
        'Print !Cow, !Dog

        Dim TheQueues As Variant[]
        TheQueues = MyQueue.AllLists

        'Stop
        !count = 40000

        While !count > 0
            !Dog = !Count
            !Cow = !Count
            '          !Cow = "hello"
            !count -= 2
        Wend

        !Done = "True"

        .NotifyStop("Dog", Me)
        .NotifyStop("Cow", Me)

    End With

    Ntask.Wait()
    Ntask2.wait()

    varMnge._Print(MyVarMem)

    Print "Delete all blocks"

    MyQueue = Null
    MyList = Null
    Vars = Null
    SymStore = Null
    MyVarMem = Null
    varMnge = Null
    VarStore = Null

    Print shmMem.GetObjectClass(Me).name;; "Completed"

    Quit 0

End

Public Sub dog_changed(varname As String, value As Variant, TimedOut As Boolean)

    If value % 10000 = 0 Then Print Application.id, "FG";; VarName;; "=";; Value;; TimedOut

End

Public Sub Cow_changed(varname As String, value As Variant, TimedOut As Boolean)

    If value % 10000 = 0 Then Print Application.id, "FG";; VarName;; "=";; Value;; TimedOut

End

Public Sub TheTask_Read(value As String)

    Print value

End

Public Sub TheTask2_read(value As String)

    Print value

End
