' Gambas module file

Public Sub Main()

    Dim MyMem As New ShmMem
    Dim a As ShmArray

    With mymem
        .PrintAllInfo()

        a = New ShmArray(MyMem, [100, 2], "ArrayDef1")

        .PrintAllInfo()
        ' MyMem.varMnge.DumpVirt(a.VirtAddress, 1000)

        a.free()
        .PrintAllInfo()

        !a = New ShmArray(mymem, [1, 2, 3], "ThisShortArray")

        !a[0, 1, 1] = "this message"
        Print !a[0, 1, 1]
    End With
    MyMem.Close()
    Quit 0

End
