' Gambas module file

Public vars As New ShmMem(200000)

Public Sub main()

    With vars

        !a = 100

        .Notify("a", Me, "a1")
        .Notify("a", Me, "a2")
        .Notify("a", Me)
        !a = 200
        .NotifyStop("a", Me, "a1")
        .NotifyStop("a", Me, "a2")
        .NotifyStop("a", Me)

        .PrintAllInfo()

    End With

    Dim again As New Define2NotifyAgain
    again.DoAgain(vars)

    Print shmMem.GetObjectClass(Me).name;; "Completed"

End

Public Sub a1(SymName As String, value As Variant, TimedOut As Boolean)

    Print "changed", SymName, value, Timedout

End

Public Sub a2(SymName As String, value As Variant, TimedOut As Boolean)

    Print "changed", SymName, value, Timedout

End

Public Sub a_changed(SymName As String, value As Variant, TimedOut As Boolean)

    Print "changed", SymName, value, Timedout

End
