' Gambas module file

Fast Unsafe

Public Sub main()

    Dim MyMem As New ShmMem

    With MyMem
        !v = [1, 2, 3, 4, 5, 6, 7, 8, 9]

        !a = [1, 2, 3, 4, 5, 6, 7, 8]

        Print !a[3]

        .["v", 1] = 100
        Let !a[1] = 1000

        Print .v[1]

        Dim a As Float = Timer
        For i As Integer = 0 To 100000
            .["v", 3] = i
        Next

        Print "Total time = 100000/"; Timer - a, !v[3], !a[2]

    End With

End
