' Gambas module file

loops As Long = 10

Public Sub main()

    Dim vmem As New ShmMem
    Dim tmp As String
    Dim starttime As Float = Timer

    For i As Integer = 0 To loops
        vmem!goat = "hello mom .." & Space(i % 1000) & ".."
        tmp = vmem!goat
        vmem!cat = "This cat.." & Space(i % 1000) & ".."
        tmp = vmem!cat
    Next

    Print "ReWrite string data";; loops;; "times, time="; Timer - starttime
    vmem.Print()

    vmem = Null

    Wait

End
