' Gambas module file

Fast Unsafe
'Extern strncpy(dest As Pointer, source As String, len As Long) In "libc:6"
Private loopcount As Integer = 100000
Private Letters As String = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

Public Sub main()

    Dim varStore As New ShmMemBlock(1128000)
    Dim varMnge As New ShmManage(varStore)
    Dim MyVarMem As New ShmVarStorage(varMnge)

    Dim symStore As New ShmMemBlock(5000000)
    Dim vars As New ShmSymbolTable(symStore, MyVarMem, False)

    Print "UseCache = "; vars.UseCache;; "' Length = "; Vars.MaxSymbols

    Dim gotit As Integer

    vars!dog = 56
    Gotit = vars!dog
    Print "The Dogs Value is ";; vars!dog
    Print "Assign/free  symbol begins for ";; loopcount;; "Loops"
    Dim starttime As Float = Timer
    For i As Integer = 0 To LoopCount
        vars!dog = i
        vars.Remove("dog")
    Next

    Print "Assign/free  symbol "; loopcount; "    Time :";; Timer - Starttime
    Print vars.text

    With vars
        !a = 1
        !aa = 8
        !AAA = 9
        !aaaaa = 10
        !b = 2
        !c = 3
        !d = 4
        !e = 5
        !fish = "hello"
        !Dish = "Bobby"

        Print vars.text
        vars.clear

        Randomize (CInt(Timer * 31))

        Dim RandomName As New String[]

        For p As Integer = 0 To (vars.length - 1) / 2
            Dim wordin As String = ""
            Dim WordLength As Integer = Rand(1, 20)
            For Q As Integer = 0 To WordLength
                Dim r As Integer = Rand(0, Letters.len - 1)
                wordin &= Letters[R]
            Next
            RandomName.Add(wordin)
        Next

        Print "Fill Symbol Table with";; RandomName.Count;; "Symbols"
        StartTime = Timer

        Dim counter As Integer = 0

        For Each s As String In RandomName
            Inc counter
            Try vars[s] = counter
            If Error Then
                Print " Assigning error :";; Error.Text;; Error.where
                Break
                ' Else
                '     counter = vars[s]
            Endif
        Next

        Print "Assigned Many variables("; vars.Count; ") to Symbol table, Time= ";; Timer - starttime

        Print Vars.TextSummary

        ' Print "Table length = "; Vars.Length
        ' Print "Sorted List Count = "; Vars.SortedList().count

        Print "Get each symbol value by name for "; RandomName.count;; "entry"
        Dim b As Integer
        starttime = Timer
        For Each s In RandomName

            b = vars[s]

        Next
        Print " Fetch Time = "; Timer - starttime
        Print .textSummary

        Print "Put Value to  each symbol  by name for "; RandomName.count;; "entry"
        b = 0
        starttime = Timer
        For Each s In RandomName
            Inc b
            vars[s] = b
        Next
        Print " Write Time = "; Timer - starttime
        Print .textSummary

        Vars.clear()

    End With

    starttime = Timer
    For i As Integer = 0 To LoopCount
        vars!dog = 56
    Next
    Print "Assign Value to symbol "; loopcount; " Time :";; Timer - Starttime

    Dim result As Integer
    starttime = Timer
    For i As Integer = 0 To LoopCount
        result = vars!dog
    Next
    Print "Get Value from symbol "; Loopcount; "  Time :";; Timer - Starttime

    varStore._free()

    symStore._free()

    Quit

End
