' Gambas module file

'Fast Unsafe

Public Sub main()

    Dim MyBlock As New ShmMemBlock(1000000)
    Dim mymem As New ShmManage(MyBlock)
    Dim StartTime As Float
    Dim pp, xx, yy, aa As Long

    Print "Starting Test.... Alloc and release blocks of memory ";
    Flush
    starttime = Timer

    For i As Integer = 0 To 500000

        pp = mymem.Alloc(500)
        xx = mymem.Alloc(1000)
        yy = mymem.Alloc(800)
        aa = mymem.Alloc(700)

        mymem.Free(xx)
        mymem.Free(aa)
        mymem.Free(yy)
        mymem.Free(pp)

        If i Mod 100000 = 0 Then Print i

    Next

    Dim Duration As Float = Timer - starttime
    Print "Alloc and free operations ";; Format(500000 * 8, "###,###,##0");; "Times, Duration = "; Duration;; " Avg seconds Per 10,000 Operations: "; (Duration / (500000.0 * 8.0) * 10000.0)
    Print
    mymem._Print()

    pp = mymem.Alloc(500)
    xx = mymem.Alloc(1000)
    yy = mymem.Alloc(800)
    aa = mymem.Alloc(700)
    mymem._Print()

    Print shmMem.GetObjectClass(Me).name;; "Completed"

End
