' Gambas module file

' Public Struct dInteger
'   Length As Long                       '' Length including header
'   Address As Long                      '' The virtual address of this block, speed pointer conversion
'   Type As Integer                      '' Type of memory
'   Value As Integer                     '' The actual value for usage
' End Struct
'Fast Unsafe

smem As ShmMem
loopcount As Integer = 1000000
startmessage As String = "Starting  string thread right now\n\r"

Public Struct messitup
    result As Long                    ' by convention result is the first field of any passed structure
    value As Long
    message As String

End Struct

Public MyMess As MessitUp

Public Sub main()

    Dim smem As ShmMem

    Print "Begin Test"
    Dim MyVar As Variant
    Dim ptr As Pointer
    smem = New ShmMem(1280000, "test", 3000, 2.1, True)
    With smem
        Print File.out.Handle
        !a = File.Load("templates/pthreadPassString.bin")                                  ' load the binary into memory
        Dim a As New ShmThread(smem, "a")
        !b = File.Load("templates/pthreadPassValue.bin")                                  ' load the binary into memory
        Dim b As New ShmThread(smem, "b")
        !c = File.Load("templates/pthreadPassStruct.bin")                                 ' load the binary into memory
        Dim c As New ShmThread(smem, "c")

        a.execute(startmessage)
        b.execute(3)
        Wait 0.1
        ptr = Alloc(SizeOf(messitup))
        Wait 0.1
        mymess = ptr
        MyMess.value = 4
        MyMess.message = " big bad string\n\r\0"
        Wait 0.1
        c.execute(ptr)
        Print "Result value from thread is ";; MyMess.result

        Print shmMem.GetObjectClass(Me).name;; "Completed"
        smem.Close()
    End With
    Quit 1

End
