' Gambas module file

' Public Struct dInteger
'   Length As Long                       '' Length including header
'   Address As Long                      '' The virtual address of this block, speed pointer conversion
'   Type As Integer                      '' Type of memory
'   Value As Integer                     '' The actual value for usage
' End Struct
'Fast Unsafe

smem As ShmMem
loopcount As Integer = 1000000

Public Sub main()

    Dim smem As ShmMem

    Print "Begin Test"
    Dim MyVar As Variant

    smem = New ShmMem(1280000, "test", 3000, 2.1, True)
    With smem
        Print File.out.Handle
        !a = File.Load("templates/pthread.bin")
        Dim b As New ShmThread(smem, "a", Null)
        Print shmMem.GetObjectClass(Me).name;; "Completed"
        smem.Close()
    End With
    Quit 1

End
