#! /bin/bash
rm pthreadStruct.o pthreadStruct.bin
gcc -g  -fPIE -finline-functions -fno-stack-protector  -c pthreadStruct.c  && \
ld  -T linkinfo -o pthreadStruct.elf pthreadStruct.o --entry threadEntry -z noexecstack
objcopy -O binary -j .text pthreadStruct.elf pthreadStruct.bin && \
objdump -d -M intel -S pthreadStruct.elf > C_dump.txt

