' Gambas module file

Public Sub main()

    Dim MyMem As New ShmMem
    Dim a As New ShmValue(mymem, 0, "newval")
    Dim b As New ShmValue[100]
    Dim c As ShmValue
    Dim d As Variant
    Dim e As ShmValue
    Dim i As Integer
    Dim ba As Integer

    Dim loops As Integer = 1000000

    a.value = "897654"
    e = New ShmValue(mymem, "newval")
    ' init the array to 100 value
    For i = 0 To b.Max
        b[i] = New ShmValue(MyMem, 0, "Value " & Str(i))
        B[i].value = i * 2
        Print b[i].value;;
    Next

    For i = 1 To 20
        c = New ShmValue(mymem, 0, "UnAssigned " & Str(i))
        c.value = "UnAssigned " & Str(i)
    Next

    ' return a list of all the values in shared memory
    d = ShmValue.list(MyMem)                      ' returns a list of all value stored in mymem, count 121

    With mymem
        Print
        Print "Begin loop of "; loops
        Dim mytime As Float = Timer
        For i = 0 To loops
            a.value = i
            ba = a.value
        Next
        Print
        Print "Time to do "; loops; " get and put operations ";; Timer - mytime
    End With

    Quit 0

End
