' Gambas module file

Public Sub main()

    Dim MyMem As New ShmMem
    Dim i As Integer
    Dim a As ShmValue

    a = New ShmValue(mymem, 0, "newval")
    Dim b As New ShmValue[100]
    Dim c As ShmValue[]
    Dim d As Variant
    d = New ShmValue(mymem, 0, "newval2")

    ' init the array to 100 value
    For i = 0 To b.Max
        b[i] = New ShmValue(MyMem, 0, "Value " & Str(i))
        B[i].value = i * 2
        Print b[i].value;;
    Next

    c = ShmValue.list(MyMem)
    Dim e As New ShmValue(mymem, "newval2")
    Print e.tag

    MyMem.close()
    Print "done"
    Quit 0

End
