' Gambas module file

Public Sub main()

    Dim TestFile As String = User.home &/ "vars" &/ "testlist"
    Dim mem As New ShmMem
    Dim aValue As New ShmValue[20]
    Dim bValue As ShmValue[]
    Dim varfile As File

    For i As Integer = 0 To aValue.Max
        aValue[i] = New ShmValue(mem, 0, "Tag" & Str(i))
        aValue[i].value = "Value" & Str(i)
    Next

    varfile = Open testfile For Write Create
    Write #varfile, aValue As Object
    Close varfile

    varfile = Open testfile For Read
    bValue = Read #varfile As Object
    Close varfile

    mem.PrintAllInfo()

    Quit 0

End