' Gambas module file

'Public Vars As ShmSymbolTable
Public Vars As Shmmem

Public Sub main()

    shmMem.ForceDelete("mydata")
    Vars = New ShmMem(1128000, "mydata")

    With vars
        !dog = 8
        !Cow = 6
        !Done = False
        !count = 0

        .Notify("Dog", Me)
        .Notify("Cow", Me)
        .Notify("Done", Me)

        ' Vars.PrintAllInfo()

        Dim Mtask As New NotifyBGTask
        Wait 5.0
        Dim Btask As New NotifyBGTask
        Wait 5.0

        While !count < 10
            !Dog = !count
            !Cow = !count
            Wait 0.03
            !Cow = "hello " & !count
            Wait 0.03
            Inc !count
        Wend

        !Done = True
        Wait 0.2

        Mtask.Wait()
        BTask.Wait()

        vars.PrintAllInfo()
        !Done = "Step one"
        vars.PrintAllInfo()
        !Done = 16
        vars.PrintAllInfo()
        !Done = "fast cars"
        vars.PrintAllInfo()
        !Done = 20
        vars.PrintAllInfo()
        !Done = "more stuff"
        vars.PrintAllInfo()
    End With
    vars.NotifyStop("Cow")
    vars.NotifyStop("Dog")
    vars.NotifyStop("Done")

    vars.PrintAllInfo()

End

Public Sub dog_changed(varname As String, value As Variant, TimedOut As Boolean)

    Print Application.id, "FG";; VarName;; "=";; Value

End

Public Sub Cow_changed(varname As String, value As Variant, TimedOut As Boolean)

    Print Application.id, "FG";; VarName;; "=";; Value

End

Public Sub Done_Changed(varname As String, value As Variant, TimedOut As Boolean)

    Print Application.id, "FG";; VarName;; "=";; Value

End

Public Sub TheTask_Read(value As String)

    Print value

End

Public Sub TheTask2_read(value As String)

    Print value

End
