' Gambas module file

''' Each of the User1-3 should be executed as seperate application
''' They give an example of sharing data between application.
''' Notifications are used to signal the apps as data changes
Public MyShare As ShmMem
Public Completed As Boolean = False

Public Sub main()

    Dim MyShare As ShmMem

    MyShare = New ShmMem(2000000, "MySharedMem", 8000)
    MyShare!Cat = "Felix"
    MyShare!Dog = "Rover"
    MyShare!Rabbit = 1000
    MyShare!Done = False

    MyShare.Notify("Cat", Me, "changes")
    MyShare.Notify("Dog", Me, "changes")
    MyShare.Notify("Rabbit", Me, "changes")
    MyShare.Notify("Done", Me, "changes")

    Print " User 2 monitoring all variables"
    While Not completed
        Wait 0.001
    Wend

    Print "User 2 Completed and exits"

End

Public Sub Changes_changed(varname As String, value As Variant, TimedOut As Boolean)

    Print varname;; "has been updated to";; value
    If VarName == "done" And value == "true" Then Completed = True

End
