' Gambas module file

Public Sub main()

    Dim TestFile As String = User.home &/ "vars" &/ "testlist"
    Dim mem As New ShmMem
    Dim AList As New ShmList(mem, 0, True, "This is a tag")
    Dim bList As ShmList
    Dim cList As ShmList
    Dim varfile As File

    For i As Integer = 0 To 20
        AList.add("Test Value" & Str(i), 200 + i, "entryTAg" & Str(i))
    Next

    varfile = Open testfile For Write Create
    Write #varfile, aList As Object
    Close varfile

    varfile = Open testfile For Read
    bList = Read #varfile As Object
    Close varfile

    varfile = Open testfile For Read
    cList = New ShmList(varfile)
    Close varfile

    Quit 0

End
